version: '2'
services:
    redis:
        image: redis:3.2.7

    postgres:
        image: postgres:9.6
        env_file:
            - ./instance/postgres.env

    webserver:
        image: opt/docker-airflow:1.8.2rc2-1
        restart: always
        depends_on:
            - postgres
            - redis
        env_file:
            - ./instance/airflow.env
            - ./instance/postgres.env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ~/Documents/Archive/SpinAppTest-b4f4c9d41a6d-airflow.json:/usr/local/airflow/gcp-airflow.json
         #   - ./requirements.txt:/requirements.txt
            - ./instance:/instance
        ports:
            - "8080:8080"
        command: webserver

    scheduler:
        image: opt/docker-airflow:1.8.2rc2-1
        restart: always
        depends_on:
            - webserver
        env_file:
            - ./instance/airflow.env
            - ./instance/postgres.env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ~/Documents/Archive/SpinAppTest-b4f4c9d41a6d-airflow.json:/usr/local/airflow/gcp-airflow.json
          #  - ./requirements.txt:/requirements.txt
            - ./instance:/instance
        command: scheduler

    worker:
        image: opt/docker-airflow:1.8.2rc2-1
        restart: always
        depends_on:
            - scheduler
        env_file:
            - ./instance/airflow.env
            - ./instance/postgres.env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ~/Documents/Archive/SpinAppTest-b4f4c9d41a6d-airflow.json:/usr/local/airflow/gcp-airflow.json
          #  - ./requirements.txt:/requirements.txt
            - ./instance:/instance
           # - ./data:/data
        command: worker
